- title: Corporate Catering
  detail: Refined Japanese cuisine tailored for events, meetings, and company celebrations.
  img: corporate.png

- title: Private Catering
  detail: Personalised catering for birthdays, anniversaries, and special gatherings at your home or chosen venue.
  img: private.png

- title: Wedding Catering
  detail: Elegant, seasonal Japanese dishes crafted to make your wedding day unforgettable.
  img: wedding.png 